---
name: Typeset

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  typeset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseoutname:
          - 'cfd-latest-preview'
          - 'cfd-old-preview'
    steps:
      - name: git checkout
        uses: actions/checkout@v7
      - name: Use old tree
        if: ${{ matrix.baseoutname == 'cfd-old-preview' }}
        run: |
          sudo apt-get install libpath-tiny-perl
          script/make-old-tree.pl
          rm -Rf cities cfd/* locdescs.*
          mv old/cities .
          mv old/cfd/* cfd
          mv old/locdescs.* .
      - name: Prepare
        id: prepare
        run: |
          echo "baseoutname=$baseoutname" >> "$GITHUB_OUTPUT"
          for f in cities/*/_all.tex ; do
            code=$( perl -ne 'print lc $1 if /^\\ChapterForState\b\S*\{(..)\}/' "$f" )
            statefile="$baseoutname-$code.tex"
            echo "\includeonly{${f%.tex}} \input{locdescs}" > $statefile
            echo "Created $statefile with \includeonly{${f%.tex}}"
          done
          tee latexmkrc <<'END'
            $dvipdf = 'dvipdfm %O -o %D %S';
          END
        env:
          baseoutname: ${{ matrix.baseoutname }}
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            locdescs.tex
            ${{ steps.prepare.outputs.baseoutname }}-*.tex
          continue_on_error: true
          args: '-pdfdvi -file-line-error -interaction=nonstopmode'
      - name: Tidy
        run: |
          mv -v locdescs.pdf "$baseoutname.pdf"
        env:
          baseoutname: ${{ steps.prepare.outputs.baseoutname }}
      - name: Store PDF files
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.baseoutname }}
          path: '*.pdf'
          retention-days: 1
          if-no-files-found: error
